/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Rank_rankLayoutRouteImport } from './routes/rank_/_rankLayout'
import { Route as Rank_rankLayoutTotalIndexRouteImport } from './routes/rank_/_rankLayout/total/index'
import { Route as Rank_rankLayoutStreakIndexRouteImport } from './routes/rank_/_rankLayout/streak/index'
import { Route as Rank_rankLayoutRepositoryIndexRouteImport } from './routes/rank_/_rankLayout/repository/index'
import { Route as Rank_rankLayoutCommitIndexRouteImport } from './routes/rank_/_rankLayout/commit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Rank_rankLayoutRoute = Rank_rankLayoutRouteImport.update({
  id: '/_rankLayout',
  getParentRoute: () => RankRoute,
} as any)
const Rank_rankLayoutTotalIndexRoute =
  Rank_rankLayoutTotalIndexRouteImport.update({
    id: '/total/',
    path: '/total/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutStreakIndexRoute =
  Rank_rankLayoutStreakIndexRouteImport.update({
    id: '/streak/',
    path: '/streak/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutRepositoryIndexRoute =
  Rank_rankLayoutRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutCommitIndexRoute =
  Rank_rankLayoutCommitIndexRouteImport.update({
    id: '/commit/',
    path: '/commit/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rank': typeof Rank_rankLayoutRouteWithChildren
  '/rank/commit': typeof Rank_rankLayoutCommitIndexRoute
  '/rank/repository': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank/streak': typeof Rank_rankLayoutStreakIndexRoute
  '/rank/total': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rank': typeof Rank_rankLayoutRouteWithChildren
  '/rank/commit': typeof Rank_rankLayoutCommitIndexRoute
  '/rank/repository': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank/streak': typeof Rank_rankLayoutStreakIndexRoute
  '/rank/total': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rank_/_rankLayout': typeof Rank_rankLayoutRouteWithChildren
  '/rank_/_rankLayout/commit/': typeof Rank_rankLayoutCommitIndexRoute
  '/rank_/_rankLayout/repository/': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank_/_rankLayout/streak/': typeof Rank_rankLayoutStreakIndexRoute
  '/rank_/_rankLayout/total/': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/rank'
    | '/rank/commit'
    | '/rank/repository'
    | '/rank/streak'
    | '/rank/total'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/rank'
    | '/rank/commit'
    | '/rank/repository'
    | '/rank/streak'
    | '/rank/total'
  id:
    | '__root__'
    | '/'
    | '/rank_/_rankLayout'
    | '/rank_/_rankLayout/commit/'
    | '/rank_/_rankLayout/repository/'
    | '/rank_/_rankLayout/streak/'
    | '/rank_/_rankLayout/total/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank_/_rankLayout': {
      id: '/rank_/_rankLayout'
      path: ''
      fullPath: '/rank'
      preLoaderRoute: typeof Rank_rankLayoutRouteImport
      parentRoute: typeof RankRoute
    }
    '/rank_/_rankLayout/total/': {
      id: '/rank_/_rankLayout/total/'
      path: '/total'
      fullPath: '/rank/total'
      preLoaderRoute: typeof Rank_rankLayoutTotalIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/streak/': {
      id: '/rank_/_rankLayout/streak/'
      path: '/streak'
      fullPath: '/rank/streak'
      preLoaderRoute: typeof Rank_rankLayoutStreakIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/repository/': {
      id: '/rank_/_rankLayout/repository/'
      path: '/repository'
      fullPath: '/rank/repository'
      preLoaderRoute: typeof Rank_rankLayoutRepositoryIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/commit/': {
      id: '/rank_/_rankLayout/commit/'
      path: '/commit'
      fullPath: '/rank/commit'
      preLoaderRoute: typeof Rank_rankLayoutCommitIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
