/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as Rank_rankLayoutRouteImport } from './routes/rank_/_rankLayout'
import { Route as Honor_honorLayoutRouteImport } from './routes/honor_/_honorLayout'
import { Route as Rank_rankLayoutTotalIndexRouteImport } from './routes/rank_/_rankLayout/total/index'
import { Route as Rank_rankLayoutStreakIndexRouteImport } from './routes/rank_/_rankLayout/streak/index'
import { Route as Rank_rankLayoutRepositoryIndexRouteImport } from './routes/rank_/_rankLayout/repository/index'
import { Route as Rank_rankLayoutCommitIndexRouteImport } from './routes/rank_/_rankLayout/commit/index'
import { Route as Honor_honorLayoutWeeklyProjectIndexRouteImport } from './routes/honor_/_honorLayout/weekly-project/index'
import { Route as Honor_honorLayoutWeeklyCommitIndexRouteImport } from './routes/honor_/_honorLayout/weekly-commit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const Rank_rankLayoutRoute = Rank_rankLayoutRouteImport.update({
  id: '/_rankLayout',
  getParentRoute: () => RankRoute,
} as any)
const Honor_honorLayoutRoute = Honor_honorLayoutRouteImport.update({
  id: '/_honorLayout',
  getParentRoute: () => HonorRoute,
} as any)
const Rank_rankLayoutTotalIndexRoute =
  Rank_rankLayoutTotalIndexRouteImport.update({
    id: '/total/',
    path: '/total/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutStreakIndexRoute =
  Rank_rankLayoutStreakIndexRouteImport.update({
    id: '/streak/',
    path: '/streak/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutRepositoryIndexRoute =
  Rank_rankLayoutRepositoryIndexRouteImport.update({
    id: '/repository/',
    path: '/repository/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Rank_rankLayoutCommitIndexRoute =
  Rank_rankLayoutCommitIndexRouteImport.update({
    id: '/commit/',
    path: '/commit/',
    getParentRoute: () => Rank_rankLayoutRoute,
  } as any)
const Honor_honorLayoutWeeklyProjectIndexRoute =
  Honor_honorLayoutWeeklyProjectIndexRouteImport.update({
    id: '/weekly-project/',
    path: '/weekly-project/',
    getParentRoute: () => Honor_honorLayoutRoute,
  } as any)
const Honor_honorLayoutWeeklyCommitIndexRoute =
  Honor_honorLayoutWeeklyCommitIndexRouteImport.update({
    id: '/weekly-commit/',
    path: '/weekly-commit/',
    getParentRoute: () => Honor_honorLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/honor': typeof Honor_honorLayoutRouteWithChildren
  '/rank': typeof Rank_rankLayoutRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/honor/weekly-commit': typeof Honor_honorLayoutWeeklyCommitIndexRoute
  '/honor/weekly-project': typeof Honor_honorLayoutWeeklyProjectIndexRoute
  '/rank/commit': typeof Rank_rankLayoutCommitIndexRoute
  '/rank/repository': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank/streak': typeof Rank_rankLayoutStreakIndexRoute
  '/rank/total': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/honor': typeof Honor_honorLayoutRouteWithChildren
  '/rank': typeof Rank_rankLayoutRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/honor/weekly-commit': typeof Honor_honorLayoutWeeklyCommitIndexRoute
  '/honor/weekly-project': typeof Honor_honorLayoutWeeklyProjectIndexRoute
  '/rank/commit': typeof Rank_rankLayoutCommitIndexRoute
  '/rank/repository': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank/streak': typeof Rank_rankLayoutStreakIndexRoute
  '/rank/total': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/honor_/_honorLayout': typeof Honor_honorLayoutRouteWithChildren
  '/rank_/_rankLayout': typeof Rank_rankLayoutRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/honor_/_honorLayout/weekly-commit/': typeof Honor_honorLayoutWeeklyCommitIndexRoute
  '/honor_/_honorLayout/weekly-project/': typeof Honor_honorLayoutWeeklyProjectIndexRoute
  '/rank_/_rankLayout/commit/': typeof Rank_rankLayoutCommitIndexRoute
  '/rank_/_rankLayout/repository/': typeof Rank_rankLayoutRepositoryIndexRoute
  '/rank_/_rankLayout/streak/': typeof Rank_rankLayoutStreakIndexRoute
  '/rank_/_rankLayout/total/': typeof Rank_rankLayoutTotalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/honor'
    | '/rank'
    | '/login'
    | '/honor/weekly-commit'
    | '/honor/weekly-project'
    | '/rank/commit'
    | '/rank/repository'
    | '/rank/streak'
    | '/rank/total'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/honor'
    | '/rank'
    | '/login'
    | '/honor/weekly-commit'
    | '/honor/weekly-project'
    | '/rank/commit'
    | '/rank/repository'
    | '/rank/streak'
    | '/rank/total'
  id:
    | '__root__'
    | '/'
    | '/honor_/_honorLayout'
    | '/rank_/_rankLayout'
    | '/login/'
    | '/honor_/_honorLayout/weekly-commit/'
    | '/honor_/_honorLayout/weekly-project/'
    | '/rank_/_rankLayout/commit/'
    | '/rank_/_rankLayout/repository/'
    | '/rank_/_rankLayout/streak/'
    | '/rank_/_rankLayout/total/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rank_/_rankLayout': {
      id: '/rank_/_rankLayout'
      path: ''
      fullPath: '/rank'
      preLoaderRoute: typeof Rank_rankLayoutRouteImport
      parentRoute: typeof RankRoute
    }
    '/honor_/_honorLayout': {
      id: '/honor_/_honorLayout'
      path: ''
      fullPath: '/honor'
      preLoaderRoute: typeof Honor_honorLayoutRouteImport
      parentRoute: typeof HonorRoute
    }
    '/rank_/_rankLayout/total/': {
      id: '/rank_/_rankLayout/total/'
      path: '/total'
      fullPath: '/rank/total'
      preLoaderRoute: typeof Rank_rankLayoutTotalIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/streak/': {
      id: '/rank_/_rankLayout/streak/'
      path: '/streak'
      fullPath: '/rank/streak'
      preLoaderRoute: typeof Rank_rankLayoutStreakIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/repository/': {
      id: '/rank_/_rankLayout/repository/'
      path: '/repository'
      fullPath: '/rank/repository'
      preLoaderRoute: typeof Rank_rankLayoutRepositoryIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/rank_/_rankLayout/commit/': {
      id: '/rank_/_rankLayout/commit/'
      path: '/commit'
      fullPath: '/rank/commit'
      preLoaderRoute: typeof Rank_rankLayoutCommitIndexRouteImport
      parentRoute: typeof Rank_rankLayoutRoute
    }
    '/honor_/_honorLayout/weekly-project/': {
      id: '/honor_/_honorLayout/weekly-project/'
      path: '/weekly-project'
      fullPath: '/honor/weekly-project'
      preLoaderRoute: typeof Honor_honorLayoutWeeklyProjectIndexRouteImport
      parentRoute: typeof Honor_honorLayoutRoute
    }
    '/honor_/_honorLayout/weekly-commit/': {
      id: '/honor_/_honorLayout/weekly-commit/'
      path: '/weekly-commit'
      fullPath: '/honor/weekly-commit'
      preLoaderRoute: typeof Honor_honorLayoutWeeklyCommitIndexRouteImport
      parentRoute: typeof Honor_honorLayoutRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
